### ISSUE TITLE
Change repository modal should be top-aligned, not centered

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-ostree#175]
![Screenshot_2021-03-24 Software Updates - garrett Rain(1)](https://user-images.githubusercontent.com/10246/112337998-ba2b3200-8cbe-11eb-8b01-d67d64d5dea8.png)

It should be aligned to the top with `pf-m-align-top` (class) or `position="top"` on `<Modal>` (React).

**Comment by KKoukiou** [comment]
This is already fixed in master.
