### ISSUE TITLE
Weird spacing at top of the page

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-ostree#177]
1. The top bar has inconsistent padding. 
2. The body has a line for some odd reason and the padding also seems off.
3. The width of the page and the cards in the page feels strange.
 
![Screenshot_2021-03-24 Software Updates - garrett Rain(5)](https://user-images.githubusercontent.com/10246/112340680-11ca9d00-8cc1-11eb-9000-ccbe19fba4eb.png)

**Comment by KKoukiou** [comment]
>     1. The top bar has inconsistent padding.
> 
>     2. The body has a line for some odd reason and the padding also seems off.
> 
>     3. The width of the page and the cards in the page feels strange.

How wide should the cards be?

**Comment by garrett** [comment]
> How wide should the cards be?

Not sure.

There's a lot of blank space at the side, but the actions would be too far away. It's fine as is for now. I've posted a redesign of the page in #176 which will probably work around this issue by using expandable lists.
