### ISSUE TITLE
Changing all JavaScript and JavaScript XML code into TypeScript and TypeScript XML.

### ISSUE THREAD

**Issue by chandakanup** [cockpit-project/cockpit-ostree#338]
This should convert app.jsx in app.tsx, changeRemoteModal.jsx in changeRemoteModal.tsx, client.js in client.ts, remotes.js in remotes.ts, test-utils.js in test-utils.js, utils.js to utils.ts in the src folder.
With TypeScript, it’s easy to read and understand components and this has IntelliSense support plus static type checking. Another additional benefit of TypeScript + React is that it provides better IntelliSense and code completion for JSX. With TypeScript, refactoring, and early detection we will have fewer bugs in code.

**Comment by martinpitt** [comment]
Moving to .ts is fine in general, but it's a *looooot* of work. I suggest looking at starter-kit first to get the integration right, which is much smaller and easier to handle. So let's continue this in https://github.com/cockpit-project/starter-kit/issues/559 . There's even an existing first pass in https://github.com/cockpit-project/starter-kit/pull/565 , but it seems for that to actually work, one needs a .ts annotation for the `cockpit` API first, see https://github.com/cockpit-project/cockpit/pull/13214 . If you are interested in working on this, this would be much appreciated!
