### ISSUE TITLE
Loading Software Updates status fails sporadically and shows "PackageKit is not installed"

### ISSUE THREAD

**Issue by dnoliver** [cockpit-project/cockpit-ostree#35]
Sporadically, the "Operating System Updates" page under "Software Update" tab fails to load, showing a "PackageKit is not installed" error (apparently, a fall-back to the default Software Updates provider)

The Firefox console shows the following message

```text
PackageKit went away from D-Bus - updates.js:43:98887
loading available updates failed: {"problem":"not-found","name":null,"message":"not-found"} - updates.js:43:126634
```

Not sure how to capture host logs for the web ui. I could provide them if you tell me how.

ostree ui appears after some reloads

**Comment by martinpitt** [comment]
Do you have some useful errors from OSTree in `sudo journalctl --since '10 mins ago'` when this happens? Does `sudo rpm-ostree status` reliably work for you?

However, this wouldn't explain why cockpit falls back to the packagekit updates page in the first place -- this should be determined by the manifest priority, not by runtime code detection. Can you please run

    cockpit-bridge --packages | grep update

a couple of times? It should show a path like /usr/lib/cockpit/cockpit-ostree, and *not* "packagekit".

**Comment by martinpitt** [comment]
@dnoliver : Which OS are you using, and which cockpit and cockpit-ostree version?

**Comment by dnoliver** [comment]
Sorry for the late response, 

I am using Fedora IoT 31 as today, but testing usually the latest rawhide

Run into a weird problem that prevented my from using cockpit! 

```text
Deployments:
● ostree://fedora-iot:fedora/devel/x86_64/iot
                   Version: 31.20191014.0 (2019-10-14T06:28:04Z)
                BaseCommit: 41d51bda1f5fe4f404997de1bf5255610143b94d43e562b2fa80cd261c087275
              GPGSignature: Valid signature by 7D22D5867F2A4236474BF7B850CB390B3C3359C4
           LayeredPackages: bzip2 cockpit cockpit-selinux dmidecode docker-compose expect git moby-engine nano openvpn setroubleshoot

  ostree://fedora-iot:fedora/devel/x86_64/iot
                   Version: 31.20191014.0 (2019-10-14T06:28:04Z)
                BaseCommit: 41d51bda1f5fe4f404997de1bf5255610143b94d43e562b2fa80cd261c087275
              GPGSignature: Valid signature by 7D22D5867F2A4236474BF7B850CB390B3C3359C4
           LayeredPackages: bzip2 cockpit cockpit-ostree cockpit-selinux dmidecode docker-compose expect git moby-engine nano openvpn setroubleshoot
```

The second compose was generated with `rpm-ostree install cockpit-ostree --reboot`, but I was never able to connect to cockpit any more, running into a `PR_CONNECT_RESET_ERROR` even after adding exceptions to the browser. Rolling back to previous compose was the only way to get cockpit working again. 

`31.20191024.0` compose without cockpit-ostree run into the same problem (so it is not this package that caused it, but the base os layer). 

Anyway, end up rebasing to rawhide (32). With rawhide, SSL certs works, but I cannot login into Cockpit. There seems to be a problem with libglib-2.0 that is throwing kernel  traps. 

Created a bug for it here https://bugzilla.redhat.com/show_bug.cgi?id=1795358
Based on this comment https://bugzilla.redhat.com/show_bug.cgi?id=1788099#c1, there is a problem with libglib2, which is described here https://bugzilla.redhat.com/show_bug.cgi?id=1772899, but it is restricted to "internal development", based on that comment a fix is on the way.

Summary, F31 does not work, neither F32, I will try my luck later this week :)

**Comment by dnoliver** [comment]
I cannot reproduce this anymore with fedora-iot 31.20200209.0. It just works now :)

**Comment by Iolaum** [comment]
I am having the same problem on an rpi4 running fedora iot:

```
$ rpm-ostree status -v
* ostree://fedora-iot:fedora/stable/aarch64/iot
                   Version: 33.20210128.0 (2021-01-28T20:42:02Z)
                BaseCommit: a4a380e3589916c6eae2fbbcb696323a7ea7af57f4ed5513dd0adaa1cdf07edb
                            |- repo-0 (2020-10-19T23:26:59Z)
                            |- repo-1 (2021-01-28T20:30:21Z)
                            |- repo-2 (2021-01-28T20:30:28Z)
                            `- repo-3 (2021-01-28T01:02:16Z)
                    Commit: d8ee40613d5929ca1c62c7b5c10b097a95d3d5cff397df01f712d1b045fbb3e5
                            |- fedora-cisco-openh264 (2020-08-25T19:10:34Z)
                            |- fedora (2020-10-19T23:26:59Z)
                            `- updates (2021-01-30T01:04:26Z)
                 StateRoot: fedora-iot
              GPGSignature: 1 signature
                            Signature made Thu Jan 28 22:42:17 2021 using RSA key ID 49FD77499570FF31
                            Good signature from "Fedora <fedora-33-primary@fedoraproject.org>"
           LayeredPackages: cockpit cockpit-podman git nano podman-compose
$ cockpit-bridge --packages | grep update
updates              Software Updates                         /usr/share/cockpit/packagekit
```

Otherwise I can log in and use cockpit normally.
