### ISSUE TITLE
Update lib/* from Cockpit, notably PF3 overrides and new RedHatText/RedHatDisplay fonts

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-ostree#47]
Cockpit-ostree is out of date with the look of Cockpit. It needs the latest version of the PF3 overrides (to look like PF4) and the new RedHat* fonts (instead of Overpass).

**Comment by martinpitt** [comment]
This is obsolete. With the PF4 port this all got cleaned up.
